# Sentry Alert Rules Configuration
# 
# These rules should be configured in the Sentry UI or via API
# This file serves as documentation for the alert configuration

alerts:
  # Error Spike Alert
  - name: "Error Spike - Sign Service"
    conditions:
      - type: "event_frequency"
        value: 10
        interval: "5m"
    actions:
      - type: "email"
        targets: ["ops@credlink.com"]
      - type: "slack"
        channel: "#alerts-production"
    filters:
      - key: "environment"
        value: "production"
      - key: "project"
        value: "sign-service"

  # New Error Type Alert
  - name: "New Error Type Detected"
    conditions:
      - type: "first_seen"
    actions:
      - type: "slack"
        channel: "#alerts-production"
      - type: "email"
        targets: ["dev@credlink.com"]
    filters:
      - key: "environment"
        value: "production"

  # Performance Degradation Alert
  - name: "Performance Degradation"
    conditions:
      - type: "transaction_duration"
        percentile: 95
        threshold: 2000  # 2 seconds
        comparison: "greater_than"
    actions:
      - type: "email"
        targets: ["ops@credlink.com"]
      - type: "pagerduty"
        service: "sign-service"
    filters:
      - key: "environment"
        value: "production"
      - key: "transaction"
        value: "/sign"

  # High Error Rate Alert
  - name: "High Error Rate"
    conditions:
      - type: "error_rate"
        value: 5  # 5% error rate
        interval: "5m"
    actions:
      - type: "email"
        targets: ["ops@credlink.com"]
      - type: "slack"
        channel: "#alerts-critical"
      - type: "pagerduty"
        service: "sign-service"
    filters:
      - key: "environment"
        value: "production"

  # Critical Error Alert
  - name: "Critical Error Detected"
    conditions:
      - type: "event_attribute"
        attribute: "level"
        value: "fatal"
    actions:
      - type: "pagerduty"
        service: "sign-service"
        severity: "critical"
      - type: "slack"
        channel: "#alerts-critical"
      - type: "email"
        targets: ["ops@credlink.com", "cto@credlink.com"]
    filters:
      - key: "environment"
        value: "production"

  # User Impact Alert
  - name: "High User Impact"
    conditions:
      - type: "users_affected"
        value: 100
        interval: "1h"
    actions:
      - type: "email"
        targets: ["ops@credlink.com"]
      - type: "slack"
        channel: "#alerts-production"
    filters:
      - key: "environment"
        value: "production"

  # Memory Leak Detection
  - name: "Potential Memory Leak"
    conditions:
      - type: "event_frequency"
        value: 5
        interval: "10m"
        filter:
          - key: "message"
            value: "out of memory"
            match: "contains"
    actions:
      - type: "email"
        targets: ["ops@credlink.com"]
      - type: "slack"
        channel: "#alerts-production"
    filters:
      - key: "environment"
        value: "production"

  # API Key Authentication Failures
  - name: "High Authentication Failure Rate"
    conditions:
      - type: "event_frequency"
        value: 20
        interval: "5m"
        filter:
          - key: "message"
            value: "Invalid API key"
            match: "contains"
    actions:
      - type: "email"
        targets: ["security@credlink.com"]
      - type: "slack"
        channel: "#security-alerts"
    filters:
      - key: "environment"
        value: "production"

# Notification Channels Configuration
notification_channels:
  email:
    - address: "ops@credlink.com"
      name: "Operations Team"
    - address: "dev@credlink.com"
      name: "Development Team"
    - address: "security@credlink.com"
      name: "Security Team"
    - address: "cto@credlink.com"
      name: "CTO"

  slack:
    - channel: "#alerts-production"
      webhook_url: "${SLACK_WEBHOOK_PRODUCTION}"
    - channel: "#alerts-critical"
      webhook_url: "${SLACK_WEBHOOK_CRITICAL}"
    - channel: "#security-alerts"
      webhook_url: "${SLACK_WEBHOOK_SECURITY}"

  pagerduty:
    - service: "sign-service"
      integration_key: "${PAGERDUTY_INTEGRATION_KEY}"

# Alert Routing Rules
routing_rules:
  - match:
      severity: "critical"
    route_to:
      - pagerduty
      - slack: "#alerts-critical"
      - email: ["ops@credlink.com", "cto@credlink.com"]

  - match:
      severity: "warning"
    route_to:
      - slack: "#alerts-production"
      - email: ["ops@credlink.com"]

  - match:
      severity: "info"
    route_to:
      - slack: "#alerts-production"

# Escalation Policies
escalation_policies:
  - name: "Production Escalation"
    steps:
      - delay: 0
        targets: ["ops@credlink.com"]
      - delay: 15m
        targets: ["cto@credlink.com"]
      - delay: 30m
        targets: ["pagerduty"]

# Muting Rules (for maintenance windows)
muting_rules:
  - name: "Deployment Window"
    schedule:
      - day: "Tuesday"
        start: "02:00"
        end: "04:00"
        timezone: "UTC"
    mute_alerts:
      - "Performance Degradation"
      - "High Error Rate"
