apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: auth-service-latency
  namespace: c2c-enterprise
spec:
  action: delay
  mode: one
  selector:
    labelSelectors:
      app: auth-service
  delay:
    latency: "100ms"
    correlation: "25"
    jitter: "50ms"
  duration: "5m"
  scheduler:
    cron: "@daily"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: webhook-service-packet-loss
  namespace: c2c-enterprise
spec:
  action: loss
  mode: one
  selector:
    labelSelectors:
      app: webhook-service
  loss:
    loss: "10"
    correlation: "25"
  duration: "2m"
  scheduler:
    cron: "@daily"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: signing-service-pod-kill
  namespace: c2c-enterprise
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: signing-service
  gracePeriodSeconds: 0
  scheduler:
    cron: "0 */6 * * *"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: admin-service-container-kill
  namespace: c2c-enterprise
spec:
  action: container-kill
  mode: one
  selector:
    labelSelectors:
      app: admin-service
  containerName: admin-service
  scheduler:
    cron: "0 */4 * * *"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: auth-service-cpu-stress
  namespace: c2c-enterprise
spec:
  mode: one
  selector:
    labelSelectors:
      app: auth-service
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "3m"
  scheduler:
    cron: "@weekly"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: signing-service-memory-stress
  namespace: c2c-enterprise
spec:
  mode: one
  selector:
    labelSelectors:
      app: signing-service
  stressors:
    memory:
      workers: 2
      size: "512Mi"
  duration: "3m"
  scheduler:
    cron: "@weekly"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: database-io-delay
  namespace: c2c-enterprise
spec:
  action: latency
  mode: one
  selector:
    labelSelectors:
      app: postgres-primary
  delay:
    latency: "200ms"
    correlation: "25"
    jitter: "100ms"
  volumePath: /var/lib/postgresql/data
  duration: "2m"
  scheduler:
    cron: "@daily"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: redis-io-error
  namespace: c2c-enterprise
spec:
  action: errno
  mode: one
  selector:
    labelSelectors:
      app: redis-cluster
  errno:
    error: "5"
  volumePath: /data
  duration: "1m"
  scheduler:
    cron: "@daily"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: external-dns-failure
  namespace: c2c-enterprise
spec:
  action: error
  mode: all
  selector:
    labelSelectors:
      app: auth-service
  dnsServer: "8.8.8.8"
  duration: "2m"
  scheduler:
    cron: "@weekly"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: external-api-timeout
  namespace: c2c-enterprise
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app: signing-service
  target: Request
  delay:
    latency: "5s"
  path: "*"
  methods:
  - POST
  timeout: "10s"
  duration: "3m"
  scheduler:
    cron: "@weekly"

---
apiVersion: chaos-mesh.org/v1alpha1
kind: PhysicalMachineChaos
metadata:
  name: node-clock-skew
  namespace: c2c-enterprise
spec:
  action: clock-skew
  mode: one
  selector:
    labelSelectors:
      node-type: application
  clock-skew:
    timeOffset: "-30s"
  duration: "2m"
  scheduler:
    cron: "@monthly"

---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: c2c-chaos-engine
  namespace: c2c-enterprise
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: "c2c-enterprise"
    applabel: "app"
    appkind: "deployment"
  chaosServiceAccount: c2c-chaos-sa
  experiments:
  - name: pod-delete
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: "60"
        - name: CHAOS_INTERVAL
          value: "10"
        - name: PODS_AFFECTED_PERC
          value: "1"
        - name: RAMP_TIME
          value: "0"
        - name: FORCE
          value: "false"
  - name: container-kill
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: "30"
        - name: CONTAINER_NAME
          value: "auth-service"
        - name: RAMP_TIME
          value: "0"
        - name: FORCE
          value: "false"
  - name: network-latency
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: "120"
        - name: NETWORK_LATENCY
          value: "200ms"
        - name: JITTER
          value: "100ms"
        - name: TARGET_CONTAINER
          value: "auth-service"
        - name: NETWORK_INTERFACE
          value: "eth0"
  - name: network-loss
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: "60"
        - name: NETWORK_PACKET_LOSS_PERCENTAGE
          value: "5"
        - name: TARGET_CONTAINER
          value: "webhook-service"
        - name: NETWORK_INTERFACE
          value: "eth0"

---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: c2c-database-chaos
  namespace: c2c-enterprise
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: "c2c-enterprise"
    applabel: "app"
    appkind: "statefulset"
  chaosServiceAccount: c2c-chaos-sa
  experiments:
  - name: pod-delete
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: "120"
        - name: CHAOS_INTERVAL
          value: "30"
        - name: PODS_AFFECTED_PERC
          value: "1"
        - name: RAMP_TIME
          value: "0"
        - name: FORCE
          value: "false"
  - name: network-partition
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: "60"
        - name: NETWORK_INTERFACE
          value: "eth0"
        - name: SEQUENCE
          value: "postgres-primary,postgres-replica"

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: chaos-scheduler
  namespace: c2c-enterprise
spec:
  schedule: "0 2 * * *" # Run at 2 AM daily
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: c2c-chaos-sa
          containers:
          - name: chaos-runner
            image: litmuschaos/chaos-runner:latest
            command:
            - /bin/bash
            - -c
            - |
              echo "Starting chaos experiments..."
              
              # Run pod delete experiment
              kubectl apply -f - <<EOF
              apiVersion: chaos-mesh.org/v1alpha1
              kind: PodChaos
              metadata:
                name: scheduled-pod-delete
                namespace: c2c-enterprise
              spec:
                action: pod-kill
                mode: one
                selector:
                  labelSelectors:
                    app: auth-service
                gracePeriodSeconds: 0
                duration: "1m"
              EOF
              
              # Wait for experiment to complete
              sleep 60
              
              # Clean up experiment
              kubectl delete podchaos scheduled-pod-delete -n c2c-enterprise || true
              
              echo "Chaos experiment completed"
          restartPolicy: OnFailure
          volumes:
          - name: kubeconfig
            secret:
              secretName: kubeconfig

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: c2c-chaos-sa
  namespace: c2c-enterprise

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: c2c-chaos-role
  namespace: c2c-enterprise
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "services", "deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["chaos-mesh.org"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["litmuschaos.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: c2c-chaos-rolebinding
  namespace: c2c-enterprise
subjects:
- kind: ServiceAccount
  name: c2c-chaos-sa
  namespace: c2c-enterprise
roleRef:
  kind: Role
  name: c2c-chaos-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-experiments-config
  namespace: c2c-enterprise
data:
  experiments.yaml: |
    experiments:
      - name: "auth-service-resilience"
        description: "Test auth service resilience under load"
        type: "load-test"
        target: "auth-service"
        parameters:
          duration: "5m"
          rps: 1000
          concurrent_users: 50
          endpoints:
            - "/api/auth/login"
            - "/api/auth/refresh"
            - "/api/auth/logout"
      
      - name: "signing-service-scalability"
        description: "Test signing service horizontal scaling"
        type: "scalability-test"
        target: "signing-service"
        parameters:
          initial_replicas: 3
          max_replicas: 10
          load_rps: 500
          scale_up_threshold: 80
          scale_down_threshold: 20
      
      - name: "database-failover"
        description: "Test database failover capabilities"
        type: "failover-test"
        target: "postgres-primary"
        parameters:
          failover_type: "graceful"
          recovery_time: "2m"
          data_consistency_check: true
      
      - name: "kafka-partition-tolerance"
        description: "Test Kafka partition tolerance"
        type: "partition-test"
        target: "kafka-cluster"
        parameters:
          partition_count: 3
          replication_factor: 3
          broker_failure_simulation: true
      
      - name: "redis-cluster-resilience"
        description: "Test Redis cluster resilience"
        type: "cluster-test"
        target: "redis-cluster"
        parameters:
          node_failure_count: 2
          failover_timeout: "30s"
          data_persistence_check: true
      
      - name: "network-partition-recovery"
        description: "Test network partition recovery"
        type: "network-test"
        target: "all-services"
        parameters:
          partition_duration: "2m"
          affected_services: ["auth-service", "webhook-service"]
          auto_recovery: true
      
      - name: "resource-exhaustion"
        description: "Test behavior under resource exhaustion"
        type: "stress-test"
        target: "signing-service"
        parameters:
          cpu_limit: "90%"
          memory_limit: "85%"
          disk_space_limit: "80%"
          duration: "3m"
      
      - name: "security-attack-simulation"
        description: "Test security under attack scenarios"
        type: "security-test"
        target: "auth-service"
        parameters:
          attack_types: ["brute-force", "ddos", "injection"]
          attack_duration: "2m"
          rate_limit_bypass: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaos-monitoring-config
  namespace: c2c-enterprise
data:
  monitoring.yaml: |
    monitoring:
      metrics:
        - name: "chaos_experiment_success_rate"
          description: "Percentage of successful chaos experiments"
          query: "chaos_experiment_success_total / chaos_experiment_total * 100"
        
        - name: "service_recovery_time"
          description: "Time taken for services to recover from chaos"
          query: "service_recovery_seconds"
        
        - name: "error_rate_during_chaos"
          description: "Error rate during chaos experiments"
          query: "rate(http_requests_total{status=~\"5..\"}[5m]) / rate(http_requests_total[5m]) * 100"
      
      alerts:
        - name: "HighChaosFailureRate"
          condition: "chaos_experiment_success_rate < 80"
          severity: "warning"
          message: "Chaos experiments failing more than 20% of the time"
        
        - name: "SlowServiceRecovery"
          condition: "service_recovery_time > 300"
          severity: "critical"
          message: "Services taking more than 5 minutes to recover from chaos"
        
        - name: "HighErrorRateDuringChaos"
          condition: "error_rate_during_chaos > 10"
          severity: "critical"
          message: "Error rate exceeding 10% during chaos experiments"
      
      dashboards:
        - name: "Chaos Engineering Overview"
          panels:
            - title: "Chaos Experiment Success Rate"
              type: "stat"
              query: "chaos_experiment_success_rate"
            
            - title: "Service Recovery Times"
              type: "graph"
              query: "service_recovery_seconds"
            
            - title: "Error Rates During Chaos"
              type: "graph"
              query: "error_rate_during_chaos"
            
            - title: "Chaos Experiment Timeline"
              type: "timeline"
              query: "chaos_experiment_duration"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: chaos-report-generator
  namespace: c2c-enterprise
spec:
  template:
    spec:
      serviceAccountName: c2c-chaos-sa
      containers:
      - name: report-generator
        image: python:3.9-slim
        command:
        - /bin/bash
        - -c
        - |
          pip install prometheus-client matplotlib pandas
          
          cat > generate_report.py << 'EOF'
          import requests
          import matplotlib.pyplot as plt
          import pandas as pd
          from datetime import datetime, timedelta
          
          # Fetch chaos metrics from Prometheus
          prometheus_url = "http://prometheus:9090"
          
          def query_prometheus(query):
              response = requests.get(f"{prometheus_url}/api/v1/query", params={"query": query})
              return response.json()
          
          # Generate chaos report
          def generate_chaos_report():
              # Get chaos experiment results
              success_rate = query_prometheus("chaos_experiment_success_total / chaos_experiment_total * 100")
              recovery_time = query_prometheus("avg(service_recovery_seconds)")
              
              # Create report
              report = f"""
              # C2C Chaos Engineering Report
              Generated: {datetime.now().isoformat()}
              
              ## Experiment Results
              - Success Rate: {success_rate['data']['result'][0]['value'][1]}%
              - Average Recovery Time: {recovery_time['data']['result'][0]['value'][1]}s
              
              ## Recommendations
              - Continue regular chaos experiments
              - Monitor service recovery patterns
              - Improve failover mechanisms
              """
              
              with open("/reports/chaos-report.md", "w") as f:
                  f.write(report)
              
              print("Chaos report generated successfully")
          
          generate_chaos_report()
          EOF
          
          python generate_report.py
          
          # Upload report to storage
          aws s3 cp /reports/chaos-report.md s3://c2c-reports/chaos/$(date +%Y-%m-%d)/chaos-report.md || true
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        volumeMounts:
        - name: reports
          mountPath: /reports
      volumes:
      - name: reports
        emptyDir: {}
      restartPolicy: OnFailure
