groups:
  - name: credlink_recording_rules
    interval: 30s
    rules:
      # Request rate by endpoint
      - record: job:http_requests:rate5m
        expr: rate(http_requests_total[5m])

      # Request rate by status code
      - record: job:http_requests:rate5m:status_code
        expr: rate(http_requests_total[5m])

      # Error rate
      - record: job:http_errors:rate5m
        expr: rate(http_requests_total{status_code=~"5.."}[5m])

      # 4XX rate
      - record: job:http_4xx:rate5m
        expr: rate(http_requests_total{status_code=~"4.."}[5m])

      # Request duration quantiles
      - record: job:http_request_duration:p50
        expr: histogram_quantile(0.50, rate(http_request_duration_seconds_bucket[5m]))

      - record: job:http_request_duration:p95
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))

      - record: job:http_request_duration:p99
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))

      # CPU usage
      - record: instance:node_cpu:utilization
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

      # Memory usage
      - record: instance:node_memory:utilization
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes

      # Disk usage
      - record: instance:node_disk:utilization
        expr: 1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})

      # Database connection pool usage
      - record: instance:db_connections:utilization
        expr: aws_rds_database_connections / 100

      # Redis memory usage
      - record: instance:redis_memory:utilization
        expr: redis_memory_used_bytes / redis_memory_max_bytes
