import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import { ProofRecord } from './proof-storage';

export class PdfGenerator {
  /**
   * Generates a PDF Certificate of Authenticity for a given proof
   */
  static async generateCertificate(proof: ProofRecord): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595.28, 841.89]); // A4 size
    const { width, height } = page.getSize();
    
    // Embed fonts
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Draw Header Background
    page.drawRectangle({
      x: 0,
      y: height - 150,
      width: width,
      height: 150,
      color: rgb(0.05, 0.1, 0.2), // Dark Blue
    });

    // Title
    page.drawText('CERTIFICATE OF AUTHENTICITY', {
      x: 50,
      y: height - 80,
      size: 24,
      font: fontBold,
      color: rgb(1, 1, 1),
    });

    page.drawText('CredLink Digital Notary Service', {
      x: 50,
      y: height - 110,
      size: 14,
      font: font,
      color: rgb(0.8, 0.8, 0.8),
    });

    // Content Section
    let yPos = height - 200;
    const lineHeight = 25;

    const drawField = (label: string, value: string) => {
      page.drawText(label, { x: 50, y: yPos, size: 10, font: fontBold, color: rgb(0.3, 0.3, 0.3) });
      page.drawText(value, { x: 200, y: yPos, size: 10, font: font, color: rgb(0, 0, 0) });
      yPos -= lineHeight;
    };

    drawField('Certificate ID:', proof.proofId);
    drawField('Digital Asset Hash:', proof.imageHash.substring(0, 32) + '...');
    drawField('Timestamp:', new Date(proof.timestamp).toLocaleString());
    drawField('Signing Algorithm:', 'RSA-2048 / SHA-256');
    drawField('Compliance Standard:', 'C2PA / CAI 2.0');
    
    // Separator
    yPos -= 20;
    page.drawLine({
      start: { x: 50, y: yPos },
      end: { x: width - 50, y: yPos },
      thickness: 1,
      color: rgb(0.9, 0.9, 0.9),
    });
    yPos -= 40;

    // Legal Statement
    const legalText = [
      'This document certifies that the digital asset identified by the cryptographic hash above',
      'was securely signed and time-stamped by the CredLink platform. The integrity of this',
      'asset has been cryptographically verified against the CredLink Root of Trust.',
      '',
      'Any modification to the original digital asset will invalidate this certificate.',
    ];

    legalText.forEach(line => {
      page.drawText(line, { x: 50, y: yPos, size: 10, font: font, color: rgb(0.2, 0.2, 0.2) });
      yPos -= 15;
    });

    // QR Code Placeholder (Visual only for now)
    page.drawRectangle({
      x: width - 150,
      y: 100,
      width: 100,
      height: 100,
      borderColor: rgb(0, 0, 0),
      borderWidth: 1,
      color: rgb(1, 1, 1)
    });
    page.drawText('SCAN TO VERIFY', {
      x: width - 145,
      y: 85,
      size: 8,
      font: fontBold,
      color: rgb(0, 0, 0),
    });

    // Footer
    page.drawText('Generated by CredLink - www.credlink.com', {
      x: 50,
      y: 30,
      size: 8,
      font: font,
      color: rgb(0.6, 0.6, 0.6),
    });

    return await pdfDoc.save();
  }
}
