# Phase 21.1 Multi-Region Topology Configuration
# ENAM Primary / WEUR Standby with Cloudflare Edge

apiVersion: v1
kind: ConfigMap
metadata:
  name: multi-region-topology
  namespace: credlink
data:
  topology.yaml: |
    # Multi-Region Topology Definition
    regions:
      primary:
        name: ENAM
        display_name: "Eastern North America"
        cloudflare_code: "enam"
        dns_zone: "credlink.com"
        
        # API Endpoints
        services:
          api_gateway:
            hostname: "api.credlink.com"
            internal_lb: "api-gateway-enam.internal"
            ports: { external: 443, internal: 8080 }
          
          sign_service:
            hostname: "sign.credlink.com" 
            internal_lb: "sign-service-enam.internal"
            ports: { external: 443, internal: 3001 }
          
          verify_service:
            hostname: "verify.credlink.com"
            internal_lb: "verify-service-enam.internal" 
            ports: { external: 443, internal: 3002 }
          
          edge_relay:
            worker_name: "c2-edge-relay-enam"
            kv_namespace: "EDGE_RELAY_ENAM"
          
        # Storage
        storage:
          r2_bucket: "manifests-enam"
          location_hint: "enam"
          replication_target: "manifests-weur"
          
        # Durable Objects
        durable_objects:
          leader_coordinator: "leader-coordinator-enam"
          job_queue: "job-queue-enam"
          
      standby:
        name: WEUR
        display_name: "Western Europe"
        cloudflare_code: "weur"
        dns_zone: "credlink.com"
        
        # API Endpoints (hot standby)
        services:
          api_gateway:
            hostname: "api-standby.credlink.com"
            internal_lb: "api-gateway-weur.internal"
            ports: { external: 443, internal: 8080 }
          
          sign_service:
            hostname: "sign-standby.credlink.com"
            internal_lb: "sign-service-weur.internal"
            ports: { external: 443, internal: 3001 }
          
          verify_service:
            hostname: "verify-standby.credlink.com"
            internal_lb: "verify-service-weur.internal"
            ports: { external: 443, internal: 3002 }
          
          edge_relay:
            worker_name: "c2-edge-relay-weur"
            kv_namespace: "EDGE_RELAY_WEUR"
          
        # Storage
        storage:
          r2_bucket: "manifests-weur"
          location_hint: "weur"
          replication_source: "manifests-enam"
          
        # Durable Objects
        durable_objects:
          leader_coordinator: "leader-coordinator-weur"
          job_queue: "job-queue-weur"

    # Cloudflare Load Balancer Configuration
    load_balancer:
      name: "credlink-lb"
      dns_name: "api.credlink.com"
      ttl: 60
      
      pools:
        primary:
          name: "pool-enam-primary"
          origins:
            - name: "api-gateway-enam"
              address: "api-gateway-enam.internal"
              port: 8080
              weight: 1
              health: "/healthz"
              health_port: 9090
          
          steering: "geo"
          regions: ["NA", "SA"]
          country_steering:
            US: "pool-enam-primary"
            CA: "pool-enam-primary"
            MX: "pool-enam-primary"
            
        standby:
          name: "pool-weur-standby"
          origins:
            - name: "api-gateway-weur"
              address: "api-gateway-weur.internal"
              port: 8080
              weight: 1
              health: "/healthz"
              health_port: 9090
          
          steering: "geo"
          regions: ["EU", "AF", "AS"]
          country_steering:
            GB: "pool-weur-standby"
            DE: "pool-weur-standby"
            FR: "pool-weur-standby"
            IT: "pool-weur-standby"
            ES: "pool-weur-standby"
            NL: "pool-weur-standby"
            BE: "pool-weur-standby"
            CH: "pool-weur-standby"
            AT: "pool-weur-standby"
            SE: "pool-weur-standby"
            NO: "pool-weur-standby"
            DK: "pool-weur-standby"
            FI: "pool-weur-standby"
            PL: "pool-weur-standby"
            CZ: "pool-weur-standby"
            HU: "pool-weur-standby"
            RO: "pool-weur-standby"
            BG: "pool-weur-standby"
            HR: "pool-weur-standby"
            SI: "pool-weur-standby"
            SK: "pool-weur-standby"
            EE: "pool-weur-standby"
            LV: "pool-weur-standby"
            LT: "pool-weur-standby"
            IE: "pool-weur-standby"
            PT: "pool-weur-standby"
            GR: "pool-weur-standby"
            TR: "pool-weur-standby"
            IL: "pool-weur-standby"
            AE: "pool-weur-standby"
            SA: "pool-weur-standby"
            ZA: "pool-weur-standby"
            EG: "pool-weur-standby"
            KE: "pool-weur-standby"
            NG: "pool-weur-standby"
            IN: "pool-weur-standby"
            PK: "pool-weur-standby"
            BD: "pool-weur-standby"
            LK: "pool-weur-standby"
            NP: "pool-weur-standby"
            MM: "pool-weur-standby"
            TH: "pool-weur-standby"
            VN: "pool-weur-standby"
            PH: "pool-weur-standby"
            MY: "pool-weur-standby"
            SG: "pool-weur-standby"
            ID: "pool-weur-standby"
            HK: "pool-weur-standby"
            TW: "pool-weur-standby"
            KR: "pool-weur-standby"
            JP: "pool-weur-standby"
            CN: "pool-weur-standby"
            AU: "pool-weur-standby"
            NZ: "pool-weur-standby"
            FJ: "pool-weur-standby"
            PG: "pool-weur-standby"
            SB: "pool-weur-standby"
            VU: "pool-weur-standby"
            NC: "pool-weur-standby"
            PF: "pool-weur-standby"
            AS: "pool-weur-standby"
            GU: "pool-weur-standby"
            MP: "pool-weur-standby"
            PW: "pool-weur-standby"
            FM: "pool-weur-standby"
            MH: "pool-weur-standby"
            KI: "pool-weur-standby"
            NR: "pool-weur-standby"
            TV: "pool-weur-standby"
            TO: "pool-weur-standby"
            WS: "pool-weur-standby"
            CK: "pool-weur-standby"
            NU: "pool-weur-standby"
            PF: "pool-weur-standby"
            WF: "pool-weur-standby"
            YT: "pool-weur-standby"
            SC: "pool-weur-standby"
            MU: "pool-weur-standby"
            RE: "pool-weur-standby"
            MG: "pool-weur-standby"
            KM: "pool-weur-standby"
            TD: "pool-weur-standby"
            CF: "pool-weur-standby"
            CM: "pool-weur-standby"
            GA: "pool-weur-standby"
            GQ: "pool-weur-standby"
            ST: "pool-weur-standby"
            AO: "pool-weur-standby"
            NA: "pool-weur-standby"
            BW: "pool-weur-standby"
            SZ: "pool-weur-standby"
            LS: "pool-weur-standby"
            ZW: "pool-weur-standby"
            MW: "pool-weur-standby"
            ZM: "pool-weur-standby"
            MZ: "pool-weur-standby"
            TZ: "pool-weur-standby"
            BI: "pool-weur-standby"
            RW: "pool-weur-standby"
            UG: "pool-weur-standby"
            ET: "pool-weur-standby"
            SO: "pool-weur-standby"
            DJ: "pool-weur-standby"
            ER: "pool-weur-standby"
            SS: "pool-weur-standby"
            SD: "pool-weur-standby"
            LY: "pool-weur-standby"
            TN: "pool-weur-standby"
            DZ: "pool-weur-standby"
            MA: "pool-weur-standby"
            EH: "pool-weur-standby"
            ML: "pool-weur-standby"
            NE: "pool-weur-standby"
            BF: "pool-weur-standby"
            CI: "pool-weur-standby"
            LR: "pool-weur-standby"
            GN: "pool-weur-standby"
            SL: "pool-weur-standby"
            GW: "pool-weur-standby"
            SN: "pool-weur-standby"
            GM: "pool-weur-standby"
            MR: "pool-weur-standby"
            TG: "pool-weur-standby"
            BJ: "pool-weur-standby"
            GH: "pool-weur-standby"
            NG: "pool-weur-standby"
            TD: "pool-weur-standby"
            CF: "pool-weur-standby"
            CM: "pool-weur-standby"
            GA: "pool-weur-standby"
            GQ: "pool-weur-standby"
            ST: "pool-weur-standby"
            AO: "pool-weur-standby"
            NA: "pool-weur-standby"
            BW: "pool-weur-standby"
            SZ: "pool-weur-standby"
            LS: "pool-weur-standby"
            ZW: "pool-weur-standby"
            MW: "pool-weur-standby"
            ZM: "pool-weur-standby"
            MZ: "pool-weur-standby"
            TZ: "pool-weur-standby"
            BI: "pool-weur-standby"
            RW: "pool-weur-standby"
            UG: "pool-weur-standby"
            ET: "pool-weur-standby"
            SO: "pool-weur-standby"
            DJ: "pool-weur-standby"
            ER: "pool-weur-standby"
            SS: "pool-weur-standby"
            SD: "pool-weur-standby"
            LY: "pool-weur-standby"
            TN: "pool-weur-standby"
            DZ: "pool-weur-standby"
            MA: "pool-weur-standby"
            EH: "pool-weur-standby"
            ML: "pool-weur-standby"
            NE: "pool-weur-standby"
            BF: "pool-weur-standby"
            CI: "pool-weur-standby"
            LR: "pool-weur-standby"
            GN: "pool-weur-standby"
            SL: "pool-weur-standby"
            GW: "pool-weur-standby"
            SN: "pool-weur-standby"
            GM: "pool-weur-standby"
            MR: "pool-weur-standby"
            TG: "pool-weur-standby"
            BJ: "pool-weur-standby"
            GH: "pool-weur-standby"
            
      failover_steering:
        type: "failover"
        primary_pool: "pool-enam-primary"
        fallback_pool: "pool-weur-standby"
        
      health_checks:
        path: "/healthz"
        port: 9090
        expected_status: 200
        expected_body: "ok"
        interval: 15
        timeout: 5
        retries: 3
        regions: ["enam", "weur", "usw", "sea"]
        
    # DNS Configuration
    dns:
      ttl: 60
      records:
        - name: "api.credlink.com"
          type: "CNAME"
          target: "credlink-lb.credlink.com"
          
        - name: "sign.credlink.com"
          type: "CNAME"
          target: "credlink-lb.credlink.com"
          
        - name: "verify.credlink.com"
          type: "CNAME"
          target: "credlink-lb.credlink.com"
          
        - name: "manifests.credlink.com"
          type: "CNAME"
          target: "credlink-lb.credlink.com"
          
    # Traffic Steering Rules
    steering:
      geo_primary:
        # Keep NA/SA traffic on primary unless unhealthy
        default_pool: "pool-enam-primary"
        fallback_pool: "pool-weur-standby"
        
      geo_standby:
        # Route EU/AF/AS to standby for better latency
        default_pool: "pool-weur-standby"
        fallback_pool: "pool-enam-primary"
        
      failover_global:
        # Global failover when primary pool unhealthy
        condition: "pool_enam_primary_unhealthy"
        action: "route_all_to_pool_weur_standby"
        
      recovery:
        # Auto-recovery when primary pool healthy again
        condition: "pool_enam_primary_healthy_for_5min"
        action: "restore_geo_steering"

---
# Cloudflare Load Balancer Manifest
apiVersion: cloudflare.com/v1
kind: LoadBalancer
metadata:
  name: credlink-lb
  namespace: credlink
spec:
  name: "credlink-lb"
  dns:
    name: "api.credlink.com"
    ttl: 60
    
  pools:
    - name: "pool-enam-primary"
      load_confidence: 100
      check_regions: ["enam"]
      origins:
        - name: "api-gateway-enam"
          address: "api-gateway-enam.internal"
          port: 8080
          weight: 1
          health: "/healthz"
          health_port: 9090
          
    - name: "pool-weur-standby"
      load_confidence: 100
      check_regions: ["weur"]
      origins:
        - name: "api-gateway-weur"
          address: "api-gateway-weur.internal"
          port: 8080
          weight: 1
          health: "/healthz"
          health_port: 9090
          
  steering:
    geo:
      default_pool: "pool-enam-primary"
      country_pools:
        US: "pool-enam-primary"
        CA: "pool-enam-primary"
        MX: "pool-enam-primary"
        GB: "pool-weur-standby"
        DE: "pool-weur-standby"
        FR: "pool-weur-standby"
        IT: "pool-weur-standby"
        ES: "pool-weur-standby"
        NL: "pool-weur-standby"
        BE: "pool-weur-standby"
        CH: "pool-weur-standby"
        AT: "pool-weur-standby"
        SE: "pool-weur-standby"
        NO: "pool-weur-standby"
        DK: "pool-weur-standby"
        FI: "pool-weur-standby"
        PL: "pool-weur-standby"
        CZ: "pool-weur-standby"
        HU: "pool-weur-standby"
        RO: "pool-weur-standby"
        BG: "pool-weur-standby"
        HR: "pool-weur-standby"
        SI: "pool-weur-standby"
        SK: "pool-weur-standby"
        EE: "pool-weur-standby"
        LV: "pool-weur-standby"
        LT: "pool-weur-standby"
        IE: "pool-weur-standby"
        PT: "pool-weur-standby"
        GR: "pool-weur-standby"
        TR: "pool-weur-standby"
        IL: "pool-weur-standby"
        AE: "pool-weur-standby"
        SA: "pool-weur-standby"
        ZA: "pool-weur-standby"
        EG: "pool-weur-standby"
        KE: "pool-weur-standby"
        NG: "pool-weur-standby"
        IN: "pool-weur-standby"
        PK: "pool-weur-standby"
        BD: "pool-weur-standby"
        LK: "pool-weur-standby"
        NP: "pool-weur-standby"
        MM: "pool-weur-standby"
        TH: "pool-weur-standby"
        VN: "pool-weur-standby"
        PH: "pool-weur-standby"
        MY: "pool-weur-standby"
        SG: "pool-weur-standby"
        ID: "pool-weur-standby"
        HK: "pool-weur-standby"
        TW: "pool-weur-standby"
        KR: "pool-weur-standby"
        JP: "pool-weur-standby"
        CN: "pool-weur-standby"
        AU: "pool-weur-standby"
        NZ: "pool-weur-standby"
        FJ: "pool-weur-standby"
        PG: "pool-weur-standby"
        SB: "pool-weur-standby"
        VU: "pool-weur-standby"
        NC: "pool-weur-standby"
        PF: "pool-weur-standby"
        AS: "pool-weur-standby"
        GU: "pool-weur-standby"
        MP: "pool-weur-standby"
        PW: "pool-weur-standby"
        FM: "pool-weur-standby"
        MH: "pool-weur-standby"
        KI: "pool-weur-standby"
        NR: "pool-weur-standby"
        TV: "pool-weur-standby"
        TO: "pool-weur-standby"
        WS: "pool-weur-standby"
        CK: "pool-weur-standby"
        NU: "pool-weur-standby"
        
    failover:
      primary_pool: "pool-enam-primary"
      fallback_pool: "pool-weur-standby"
      
  health_checks:
    path: "/healthz"
    port: 9090
    expected_status: 200
    expected_body: "ok"
    interval: 15
    timeout: 5
    retries: 3
    regions: ["enam", "weur", "usw", "sea"]

---
# Regional Service Deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-enam
  namespace: credlink
  labels:
    app: api-gateway
    region: enam
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
      region: enam
  template:
    metadata:
      labels:
        app: api-gateway
        region: enam
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values: ["us-east-1"]
      containers:
      - name: api-gateway
        image: "credlink/api-gateway:latest"
        ports:
        - containerPort: 8080
        - containerPort: 9090  # Health check port
        env:
        - name: REGION
          value: "enam"
        - name: IS_PRIMARY
          value: "true"
        - name: STANDBY_REGION
          value: "weur"
        - name: R2_BUCKET
          value: "manifests-enam"
        - name: REPLICATION_BUCKET
          value: "manifests-weur"
        - name: DO_COORDINATOR
          value: "leader-coordinator-enam"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-weur
  namespace: credlink
  labels:
    app: api-gateway
    region: weur
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
      region: weur
  template:
    metadata:
      labels:
        app: api-gateway
        region: weur
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values: ["eu-west-1"]
      containers:
      - name: api-gateway
        image: "credlink/api-gateway:latest"
        ports:
        - containerPort: 8080
        - containerPort: 9090  # Health check port
        env:
        - name: REGION
          value: "weur"
        - name: IS_PRIMARY
          value: "false"
        - name: PRIMARY_REGION
          value: "enam"
        - name: R2_BUCKET
          value: "manifests-weur"
        - name: REPLICATION_SOURCE
          value: "manifests-enam"
        - name: DO_COORDINATOR
          value: "leader-coordinator-weur"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
