import json
import os
import boto3
import datetime
import urllib3

# Initialize clients
secrets_client = boto3.client('secretsmanager')
http = urllib3.PoolManager()

def handler(event, context):
    """
    Lambda function to process security events and send alerts
    """
    try:
        # Extract event details
        detail = event.get('detail', {})
        event_name = detail.get('eventName', 'Unknown')
        event_source = detail.get('eventSource', 'Unknown')
        user_identity = detail.get('userIdentity', {})
        request_parameters = detail.get('requestParameters', {})
        
        # Build security alert message
        alert_message = build_alert_message(
            event_name=event_name,
            event_source=event_source,
            user_identity=user_identity,
            request_parameters=request_parameters,
            event_time=event.get('time', datetime.datetime.utcnow().isoformat())
        )
        
        # Send alerts
        send_email_alert(alert_message)
        send_webhook_alert(alert_message)
        
        # Log the alert
        print(f"Security alert processed: {event_name} by {user_identity.get('arn', 'Unknown')}")
        
        return {
            'statusCode': 200,
            'body': json.dumps({'message': 'Security alert processed successfully'})
        }
        
    except Exception as e:
        print(f"Error processing security alert: {str(e)}")
        return {
            'statusCode': 500,
            'body': json.dumps({'error': str(e)})
        }

def build_alert_message(event_name, event_source, user_identity, request_parameters, event_time):
    """
    Build a comprehensive security alert message
    """
    severity = determine_severity(event_name, event_source)
    
    message = f"""
🚨 SECURITY ALERT - {severity.upper()} 🚨

Event Details:
- Event: {event_name}
- Source: {event_source}
- Time: {event_time}
- User: {user_identity.get('arn', 'Unknown')}
- User Type: {user_identity.get('type', 'Unknown')}
- Source IP: {user_identity.get('sourceIPAddress', 'Unknown')}

Request Parameters:
{json.dumps(request_parameters, indent=2, default=str)}

Security Assessment:
- Risk Level: {severity}
- Requires Investigation: {'Yes' if severity in ['HIGH', 'CRITICAL'] else 'No'}
- Recommended Action: {get_recommended_action(event_name, severity)}

This alert was generated by the CredLink security monitoring system.
    """
    
    return message.strip()

def determine_severity(event_name, event_source):
    """
    Determine the severity level of a security event
    """
    high_risk_events = [
        'DeleteUser', 'DeleteRole', 'DeletePolicy', 'DeleteBucket',
        'DisableKey', 'ScheduleKeyDeletion', 'DeleteAccessKey',
        'UpdateDistribution', 'DeleteFunction', 'RemovePermission'
    ]
    
    medium_risk_events = [
        'CreateUser', 'CreateRole', 'CreatePolicy', 'CreateBucket',
        'EnableKey', 'CreateAccessKey', 'AddPermission'
    ]
    
    if event_name in high_risk_events:
        return 'CRITICAL'
    elif event_name in medium_risk_events:
        return 'HIGH'
    elif 'Delete' in event_name or 'Remove' in event_name:
        return 'MEDIUM'
    else:
        return 'LOW'

def get_recommended_action(event_name, severity):
    """
    Get recommended action based on event and severity
    """
    if severity == 'CRITICAL':
        return 'IMMEDIATE INVESTIGATION REQUIRED - Contact security team'
    elif severity == 'HIGH':
        return 'Investigate within 1 hour - Verify authorization'
    elif severity == 'MEDIUM':
        return 'Review within 24 hours - Confirm business need'
    else:
        return 'Log for audit - Monitor for patterns'

def send_email_alert(message):
    """
    Send email alert (placeholder - implement with SES or other email service)
    """
    alert_email = os.environ.get('ALERT_EMAIL')
    if not alert_email:
        print("No alert email configured")
        return
    
    try:
        # This is a placeholder - implement with AWS SES or other email service
        print(f"Email alert would be sent to {alert_email}")
        print(f"Message: {message[:200]}...")
        
        # Example SES implementation (would need SES configuration):
        # ses_client = boto3.client('ses')
        # ses_client.send_email(
        #     Source='alerts@c2concierge.com',
        #     Destination={'ToAddresses': [alert_email]},
        #     Message={
        #         'Subject': {'Data': 'CredLink Security Alert'},
        #         'Body': {'Text': {'Data': message}}
        #     }
        # )
        
    except Exception as e:
        print(f"Failed to send email alert: {str(e)}")

def send_webhook_alert(message):
    """
    Send webhook alert to Slack or other monitoring system
    """
    webhook_url = os.environ.get('ALERT_WEBHOOK')
    if not webhook_url:
        print("No webhook URL configured")
        return
    
    try:
        # Format message for Slack
        slack_message = {
            "text": "🚨 CredLink Security Alert",
            "attachments": [
                {
                    "color": "danger" if "CRITICAL" in message else "warning",
                    "text": message
                }
            ]
        }
        
        # Send to webhook
        encoded_msg = json.dumps(slack_message).encode('utf-8')
        response = http.request(
            'POST',
            webhook_url,
            body=encoded_msg,
            headers={'Content-Type': 'application/json'}
        )
        
        if response.status != 200:
            print(f"Webhook failed with status {response.status}")
        else:
            print("Webhook alert sent successfully")
            
    except Exception as e:
        print(f"Failed to send webhook alert: {str(e)}")

def analyze_security_pattern(event):
    """
    Analyze events for security patterns (future enhancement)
    """
    # This could be expanded to detect:
    # - Multiple failed authentication attempts
    # - Unusual access patterns
    # - Privilege escalation attempts
    # - Data exfiltration patterns
    
    pass
