#!/usr/bin/env node

/**
 * C2C Hostile CDN Gauntlet - HTML Report Generator
 * Creates interactive HTML reports with matrix visualization
 */

import * as fs from 'fs';
import * as path from 'path';
import { TestResult, TestSummary } from '../run';

interface ReportConfig {
  title: string;
  logo_url: string;
  footer_text: string;
  css_theme: string;
}

class HTMLReportGenerator {
  private config: ReportConfig;

  constructor(config: Partial<ReportConfig> = {}) {
    this.config = {
      title: 'C2C Hostile CDN Gauntlet Report',
      logo_url: 'https://c2concierge.com/logo.png',
      footer_text: 'Generated by C2C Hostile CDN Gauntlet',
      css_theme: 'modern',
      ...config
    };
  }

  /**
   * Generate CSS styles
   */
  private generateCSS(): string {
    return `
      <style>
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }

        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          line-height: 1.6;
          color: #333;
          background: #f8fafc;
        }

        .container {
          max-width: 1400px;
          margin: 0 auto;
          padding: 20px;
        }

        .header {
          background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
          color: white;
          padding: 40px 20px;
          border-radius: 12px;
          margin-bottom: 30px;
          box-shadow: 0 10px 30px rgba(0,0,0,0.1);
        }

        .header h1 {
          font-size: 2.5rem;
          margin-bottom: 10px;
        }

        .header .subtitle {
          font-size: 1.2rem;
          opacity: 0.9;
        }

        .summary-cards {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 20px;
          margin-bottom: 30px;
        }

        .card {
          background: white;
          padding: 25px;
          border-radius: 12px;
          box-shadow: 0 4px 15px rgba(0,0,0,0.08);
          border-left: 4px solid #667eea;
        }

        .card h3 {
          font-size: 0.9rem;
          text-transform: uppercase;
          color: #666;
          margin-bottom: 10px;
        }

        .card .value {
          font-size: 2rem;
          font-weight: bold;
          color: #333;
        }

        .card .unit {
          font-size: 1rem;
          color: #666;
          margin-left: 5px;
        }

        .success { color: #10b981; }
        .warning { color: #f59e0b; }
        .error { color: #ef4444; }

        .matrix-container {
          background: white;
          border-radius: 12px;
          padding: 30px;
          box-shadow: 0 4px 15px rgba(0,0,0,0.08);
          margin-bottom: 30px;
          overflow-x: auto;
        }

        .matrix-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 20px;
        }

        .matrix-header h2 {
          font-size: 1.5rem;
          color: #333;
        }

        .filters {
          display: flex;
          gap: 10px;
        }

        .filter-btn {
          padding: 8px 16px;
          border: 1px solid #ddd;
          background: white;
          border-radius: 6px;
          cursor: pointer;
          transition: all 0.2s;
        }

        .filter-btn:hover {
          background: #f3f4f6;
        }

        .filter-btn.active {
          background: #667eea;
          color: white;
          border-color: #667eea;
        }

        .matrix-table {
          width: 100%;
          border-collapse: collapse;
          font-size: 0.9rem;
        }

        .matrix-table th,
        .matrix-table td {
          padding: 12px 8px;
          text-align: center;
          border: 1px solid #e5e7eb;
        }

        .matrix-table th {
          background: #f9fafb;
          font-weight: 600;
          color: #374151;
        }

        .matrix-table .provider-header {
          background: #f3f4f6;
          font-weight: bold;
          text-align: left;
        }

        .matrix-table .route-header {
          background: #fef3c7;
          font-weight: 600;
        }

        .cell {
          cursor: pointer;
          transition: background-color 0.2s;
          position: relative;
        }

        .cell:hover {
          background: #f9fafb;
        }

        .cell.pass {
          background: #d1fae5;
        }

        .cell.pass:hover {
          background: #a7f3d0;
        }

        .cell.fail {
          background: #fee2e2;
        }

        .cell.fail:hover {
          background: #fecaca;
        }

        .cell-content {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 5px;
        }

        .status-icon {
          width: 12px;
          height: 12px;
          border-radius: 50%;
        }

        .status-icon.pass {
          background: #10b981;
        }

        .status-icon.fail {
          background: #ef4444;
        }

        .provider-breakdown {
          background: white;
          border-radius: 12px;
          padding: 30px;
          box-shadow: 0 4px 15px rgba(0,0,0,0.08);
          margin-bottom: 30px;
        }

        .provider-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
          gap: 20px;
          margin-top: 20px;
        }

        .provider-card {
          border: 1px solid #e5e7eb;
          border-radius: 8px;
          padding: 20px;
        }

        .provider-card h4 {
          font-size: 1.1rem;
          margin-bottom: 15px;
          color: #333;
        }

        .metric-row {
          display: flex;
          justify-content: space-between;
          margin-bottom: 8px;
        }

        .metric-label {
          color: #666;
        }

        .metric-value {
          font-weight: 600;
        }

        .tooltip {
          position: absolute;
          background: #1f2937;
          color: white;
          padding: 8px 12px;
          border-radius: 6px;
          font-size: 0.8rem;
          z-index: 1000;
          pointer-events: none;
          opacity: 0;
          transition: opacity 0.2s;
          max-width: 300px;
        }

        .tooltip.show {
          opacity: 1;
        }

        .footer {
          text-align: center;
          padding: 40px 20px;
          color: #666;
          border-top: 1px solid #e5e7eb;
          margin-top: 50px;
        }

        .p0-banner {
          background: #dc2626;
          color: white;
          padding: 15px 20px;
          border-radius: 8px;
          margin-bottom: 20px;
          text-align: center;
          font-weight: 600;
        }

        .success-banner {
          background: #059669;
          color: white;
          padding: 15px 20px;
          border-radius: 8px;
          margin-bottom: 20px;
          text-align: center;
          font-weight: 600;
        }

        @media (max-width: 768px) {
          .container {
            padding: 10px;
          }
          
          .header h1 {
            font-size: 1.8rem;
          }
          
          .matrix-table {
            font-size: 0.8rem;
          }
          
          .matrix-table th,
          .matrix-table td {
            padding: 8px 4px;
          }
        }
      </style>
    `;
  }

  /**
   * Generate JavaScript for interactivity
   */
  private generateJavaScript(): string {
    return `
      <script>
        // Filter functionality
        function filterMatrix(provider, route) {
          const cells = document.querySelectorAll('.matrix-cell');
          cells.forEach(cell => {
            const cellProvider = cell.dataset.provider;
            const cellRoute = cell.dataset.route;
            
            const showProvider = !provider || cellProvider === provider;
            const showRoute = !route || cellRoute === route;
            
            cell.style.display = showProvider && showRoute ? '' : 'none';
          });
        }

        // Tooltip functionality
        function setupTooltips() {
          const cells = document.querySelectorAll('.cell');
          const tooltip = document.getElementById('tooltip');
          
          cells.forEach(cell => {
            cell.addEventListener('mouseenter', (e) => {
              const content = cell.querySelector('.cell-content');
              if (content) {
                tooltip.innerHTML = content.getAttribute('data-tooltip') || '';
                tooltip.classList.add('show');
              }
            });
            
            cell.addEventListener('mousemove', (e) => {
              tooltip.style.left = e.pageX + 10 + 'px';
              tooltip.style.top = e.pageY + 10 + 'px';
            });
            
            cell.addEventListener('mouseleave', () => {
              tooltip.classList.remove('show');
            });
          });
        }

        // Click to open asset
        function openAsset(url) {
          window.open(url, '_blank');
        }

        // Initialize when DOM is loaded
        document.addEventListener('DOMContentLoaded', () => {
          setupTooltips();
          
          // Setup filter buttons
          const filterButtons = document.querySelectorAll('.filter-btn');
          filterButtons.forEach(btn => {
            btn.addEventListener('click', () => {
              // Remove active class from all buttons
              filterButtons.forEach(b => b.classList.remove('active'));
              // Add active class to clicked button
              btn.classList.add('active');
              
              const filter = btn.getAttribute('data-filter');
              const [type, value] = filter.split(':');
              
              if (type === 'all') {
                filterMatrix(null, null);
              } else if (type === 'provider') {
                filterMatrix(value === 'all' ? null : value, null);
              } else if (type === 'route') {
                filterMatrix(null, value === 'all' ? null : value);
              }
            });
          });
        });
      </script>
    `;
  }

  /**
   * Generate summary cards HTML
   */
  private generateSummaryCards(summary: TestSummary): string {
    const remoteRate = summary.remote_survival_rate;
    const embedRate = summary.embed_survival_rate;
    const totalTests = summary.total_tests;

    return `
      <div class="summary-cards">
        <div class="card">
          <h3>Total Tests</h3>
          <div class="value">${totalTests.toLocaleString()}</div>
        </div>
        <div class="card">
          <h3>Remote Survival</h3>
          <div class="value ${remoteRate >= 99.9 ? 'success' : remoteRate >= 95 ? 'warning' : 'error'}">
            ${remoteRate.toFixed(1)}<span class="unit">%</span>
          </div>
        </div>
        <div class="card">
          <h3>Embed Survival</h3>
          <div class="value ${embedRate >= 50 ? 'success' : embedRate >= 25 ? 'warning' : 'error'}">
            ${embedRate.toFixed(1)}<span class="unit">%</span>
          </div>
        </div>
        <div class="card">
          <h3>Runtime</h3>
          <div class="value">${(summary.performance.total_runtime / 1000).toFixed(1)}<span class="unit">s</span>
          </div>
        </div>
      </div>
    `;
  }

  /**
   * Generate provider breakdown HTML
   */
  private generateProviderBreakdown(summary: TestSummary): string {
    const providerCards = Object.entries(summary.provider_results).map(([provider, results]) => `
      <div class="provider-card">
        <h4>${provider.charAt(0).toUpperCase() + provider.slice(1)}</h4>
        <div class="metric-row">
          <span class="metric-label">Tests:</span>
          <span class="metric-value">${results.total}</span>
        </div>
        <div class="metric-row">
          <span class="metric-label">Remote:</span>
          <span class="metric-value ${results.remote_rate >= 99.9 ? 'success' : results.remote_rate >= 95 ? 'warning' : 'error'}">
            ${results.remote_rate.toFixed(1)}%
          </span>
        </div>
        <div class="metric-row">
          <span class="metric-label">Embed:</span>
          <span class="metric-value ${results.embed_rate >= 50 ? 'success' : results.embed_rate >= 25 ? 'warning' : 'error'}">
            ${results.embed_rate.toFixed(1)}%
          </span>
        </div>
      </div>
    `).join('');

    return `
      <div class="provider-breakdown">
        <h2>Provider Performance</h2>
        <div class="provider-grid">
          ${providerCards}
        </div>
      </div>
    `;
  }

  /**
   * Generate matrix table HTML
   */
  private generateMatrixTable(results: TestResult[]): string {
    // Group results by provider and route
    const grouped: Record<string, Record<string, TestResult[]>> = {};
    
    results.forEach(result => {
      if (!grouped[result.provider]) {
        grouped[result.provider] = {};
      }
      if (!grouped[result.provider]![result.route]) {
        grouped[result.provider]![result.route] = [];
      }
      grouped[result.provider]![result.route]!.push(result);
    });

    const providers = Object.keys(grouped).sort();
    const routes = ['preserve-embed', 'strip-happy', 'remote-only'];
    const transforms = [...new Set(results.map(r => r.transform))].sort();

    const tableRows: string[] = [];

    providers.forEach(provider => {
      // Provider header row
      tableRows.push(`
        <tr>
          <td colspan="${transforms.length + 2}" class="provider-header">
            ${provider.charAt(0).toUpperCase() + provider.slice(1)}
          </td>
        </tr>
      `);

      routes.forEach(route => {
        // Route header row
        tableRows.push(`
          <tr>
            <td class="route-header" colspan="2">${route.replace('-', ' ')}</td>
            ${transforms.map(() => '<td class="route-header"></td>').join('')}
          </tr>
        `);

        // Transform header row
        tableRows.push(`
          <tr>
            <th>Transform</th>
            <th>Asset</th>
            ${transforms.map(t => `<th>${t.replace('_', ' ')}</th>`).join('')}
          </tr>
        `);

        // Data rows for each asset
        const routeResults = grouped[provider]![route] || [];
        const assets = [...new Set(routeResults.map(r => r.asset))].sort();

        assets.forEach(asset => {
          const assetResults = routeResults.filter(r => r.asset === asset);
          
          tableRows.push(`
            <tr>
              <td></td>
              <td>${asset}</td>
              ${transforms.map(transform => {
                const result = assetResults.find(r => r.transform === transform);
                if (!result) return '<td></td>';
                
                const statusClass = result.verdict_remote === 'PASS' ? 'pass' : 'fail';
                const statusIcon = result.verdict_remote === 'PASS' ? '✓' : '✗';
                const tooltip = `${result.provider} - ${result.route} - ${result.transform}\\nRemote: ${result.verdict_remote}\\nEmbed: ${result.verdict_embed}\\n${result.why_remote || result.why_embed || ''}`;
                
                return `
                  <td class="cell ${statusClass} matrix-cell" 
                      data-provider="${provider}" 
                      data-route="${route}"
                      onclick="openAsset('${result.asset_url}')">
                    <div class="cell-content" data-tooltip="${tooltip}">
                      <span class="status-icon ${statusClass}"></span>
                      <span>${statusIcon}</span>
                    </div>
                  </td>
                `;
              }).join('')}
            </tr>
          `);
        });
      });
    });

    return `
      <div class="matrix-container">
        <div class="matrix-header">
          <h2>Test Matrix</h2>
          <div class="filters">
            <button class="filter-btn active" data-filter="all">All</button>
            <button class="filter-btn" data-filter="provider:all">All Providers</button>
            ${providers.map(p => `<button class="filter-btn" data-filter="provider:${p}">${p}</button>`).join('')}
            <button class="filter-btn" data-filter="route:all">All Routes</button>
            ${routes.map(r => `<button class="filter-btn" data-filter="route:${r}">${r.replace('-', ' ')}</button>`).join('')}
          </div>
        </div>
        <table class="matrix-table">
          ${tableRows.join('')}
        </table>
      </div>
    `;
  }

  /**
   * Generate complete HTML report
   */
  public generateHTML(results: TestResult[], summary: TestSummary): string {
    const timestamp = new Date().toISOString();
    const isP0 = summary.remote_survival_rate < 99.9;

    return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${this.config.title} - ${timestamp.split('T')[0]}</title>
        ${this.generateCSS()}
      </head>
      <body>
        <div class="container">
          <header class="header">
            <h1>${this.config.title}</h1>
            <div class="subtitle">
              Generated on ${new Date(timestamp).toLocaleString()} • 
              ${summary.total_tests.toLocaleString()} tests • 
              ${isP0 ? '🚨 P0 INCIDENT' : '✅ OPERATIONAL'}
            </div>
          </header>

          ${isP0 ? 
            '<div class="p0-banner">🚨 P0 INCIDENT: Remote survival below 99.9% threshold</div>' :
            '<div class="success-banner">✅ All systems operational: Remote survival ≥ 99.9%</div>'
          }

          ${this.generateSummaryCards(summary)}
          ${this.generateProviderBreakdown(summary)}
          ${this.generateMatrixTable(results)}

          <footer class="footer">
            <p>${this.config.footer_text}</p>
            <p>Report generated: ${new Date(timestamp).toLocaleString()}</p>
          </footer>
        </div>

        <div id="tooltip" class="tooltip"></div>
        
        <script>
          // Inject actual data
          const testData = {
            results: ${JSON.stringify(results)},
            summary: ${JSON.stringify(summary)}
          };
        </script>
        ${this.generateJavaScript()}
      </body>
      </html>
    `;
  }

  /**
   * Save HTML report to file
   */
  public saveReport(results: TestResult[], summary: TestSummary, outputPath: string): void {
    const html = this.generateHTML(results, summary);
    
    // Ensure output directory exists
    const dir = path.dirname(outputPath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    fs.writeFileSync(outputPath, html);
    console.log(`HTML report saved to: ${outputPath}`);
  }
}

// CLI interface
if (require.main === module) {
  const resultsPath = process.argv[2];
  const outputPath = process.argv[3] || './report.html';
  
  if (!resultsPath) {
    console.error('Usage: ts-node html.ts <results.json> [output.html]');
    process.exit(1);
  }

  try {
    const results = JSON.parse(fs.readFileSync(resultsPath, 'utf8'));
    const summary = JSON.parse(fs.readFileSync(resultsPath.replace('results', 'summary'), 'utf8'));
    
    const generator = new HTMLReportGenerator();
    generator.saveReport(results, summary, outputPath);
  } catch (error) {
    console.error('Failed to generate HTML report:', error);
    process.exit(1);
  }
}

export { HTMLReportGenerator };
