# S-13: DDoS Protection - Cloudflare WAF Rules

waf_rules:
  # Rate limiting rules
  # Balanced approach: Prevent abuse while allowing legitimate high-volume usage
  - name: "Sign endpoint rate limit"
    expression: '(http.request.uri.path eq "/sign")'
    action: rate_limit
    rate_limit:
      threshold: 100  # Increased from 10 to 100 requests/minute
      period: 60      # seconds
      mitigation_timeout: 300 # 5 minutes
      # Note: Authenticated users can be given higher limits via API key tier
      # Consider implementing tiered rate limits:
      # - Free tier: 100/min
      # - Pro tier: 500/min
      # - Enterprise: 5000/min
    enabled: true

  - name: "Verify endpoint rate limit"
    expression: '(http.request.uri.path eq "/verify")'
    action: rate_limit
    rate_limit:
      threshold: 100
      period: 60
      mitigation_timeout: 60
    enabled: true

  # Block known bad user agents
  - name: "Block malicious bots"
    expression: '(http.user_agent contains "sqlmap") or (http.user_agent contains "nikto") or (http.user_agent contains "nmap")'
    action: block
    enabled: true

  # Block requests with no user agent
  - name: "Require user agent"
    expression: '(not http.user_agent)'
    action: challenge
    enabled: true

  # Geo-blocking (example - adjust as needed)
  - name: "Geo-restrictions"
    expression: '(ip.geoip.country in {"CN" "RU" "KP"})'
    action: challenge
    enabled: false # Disabled by default

  # SQL injection protection
  - name: "SQL injection patterns"
    expression: '(http.request.uri.query contains "union select") or (http.request.uri.query contains "1=1") or (http.request.uri.query contains "drop table")'
    action: block
    enabled: true

  # Large request body protection
  - name: "Block oversized requests"
    expression: '(http.request.body.size gt 52428800)' # 50MB
    action: block
    enabled: true

  # API abuse detection
  - name: "Suspicious API activity"
    expression: '(cf.threat_score gt 50)'
    action: challenge
    enabled: true

  # L7 DDoS protection
  - name: "HTTP flood protection"
    expression: '(cf.bot_management.score lt 30)'
    action: managed_challenge
    enabled: true

# Managed rulesets
managed_rulesets:
  - name: "Cloudflare Managed Ruleset"
    enabled: true
  
  - name: "Cloudflare OWASP Core Ruleset"
    enabled: true
    sensitivity: medium

# Security level
security_level: high

# Bot fight mode
bot_fight_mode: true

# Challenge passage
challenge_passage: 30 # minutes

# Browser integrity check
browser_integrity_check: true

# Hotlink protection
hotlink_protection:
  enabled: true
  allowed_domains:
    - "credlink.com"
    - "*.credlink.com"
